### ISSUE TITLE
【建议】希望支持编辑和预览调换位置

### ISSUE THREAD

**Issue by SuperVisen** [purocean/yn#92]

**Comment by SuperVisen** [comment]
目前个人痛点：
两个板块位置不支持拖动大小
设置没有只打开一个文件这个选项，会有很多文件同时在导航栏

**Comment by SuperVisen** [comment]
预览内要是能进行同步编辑，基本上这个产品就是神

**Comment by SuperVisen** [comment]
预览总是无法和编辑的视角对齐，很多时候没法做到边编辑边预览

**Comment by purocean** [comment]
Yank Note 及其开放，你可以自己写插件或样式试试

- 比如编辑和预览对调位置，可以自定义 CSS
```css
#app > div > div.main > div.right > div.content > div.editor {
  order: 2;
}

```

- 只打开一个文件，可以写插件重设打开的标签

其他问题：

- 预览即所得编辑，不会做。
- 预览同步滚动，这块体验还要持续优化，但是目前不会是重点
